### ISSUE TITLE
add getBinaryMaze method to Maze Object class

### ISSUE THREAD

**Issue by stevendbp** [AaronCoplan/MazeSolver#16]

**Comment by AaronCoplan** [comment]
Is this still needed?

**Comment by stevendbp** [comment]
It would make complex solving much easier.

**Comment by AaronCoplan** [comment]
Ok, I'll write this soon.

**Comment by AaronCoplan** [comment]
Fully working getBinaryMaze() method has been added to the maze class. @stevendbp
